### ISSUE TITLE
Create version 2 parser

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/parser-go#1]
This issue serves as an "Epic" in Zenhub. If you're reading this in Github, please ignore.

**Comment by RobertDiebels** [comment]
Which issues need to be resolved for this epic? I've looked through the current issues and their threads. I think most of them already have assignees but the issues don't reflect this. In any case, maybe adding a list of the issues this epic depends upon would be nice?

**Comment by fmvilas** [comment]
Yeah, this is just for our Zenhub to work. I'll invite you.

**Comment by joshk0** [comment]
This was solved in #43 . Right?

**Comment by derberg** [comment]
@joshk0 not entirely. Parser is there but the basic one. We use ZenHub in AsyncAPI to manage work on all repositories in one view. Once you install ZenHub browser ZenHub plugin you can see some more metadata here. This issue has some still open issues linked in. Pending thigs are some additional parser "plugins", like parsing of schemas provided with OpenAPI or Avro
