### ISSUE TITLE
Release all changes since v0.4.2

### ISSUE THREAD

**Issue by ivan-penchev** [asyncapi/parser-go#204]
#### Reason/Context
Please try answering few of those questions
- We need this this so we could get support for latest version of async schema implemented by @smoya  here https://github.com/asyncapi/parser-go/issues/190
- This will help the community, to adopt further AsyncAPI standard, by having highly supported tools
- Further development of the tool

#### Description
I would like to fetch all the changes since Aug 8, 2022 and create a release, since this is a 1 year of changes there might be some breaking changes, but it does not appear so on the surface.

**Comment by ivan-penchev** [comment]
@smoya  sorry to tag you, but can you check this one out?

**Comment by smoya** [comment]
> @smoya sorry to tag you, but can you check this one out?

You don't need to apologize! I wonder why merging https://github.com/asyncapi/parser-go/pull/193 didn't trigger a release. I'm forcing a new release to happen in https://github.com/asyncapi/parser-go/pull/205. I need @magicmatatjahu +1 otherwise I can’t merge it unfortunately.

**Comment by smoya** [comment]
Release didn't happen as for some reason tests failed after merge... Removing Gomega that was the culprit as we don't need it anymore https://github.com/asyncapi/parser-go/pull/206 cc @magicmatatjahu

**Comment by smoya** [comment]
More problems with the release https://github.com/asyncapi/parser-go/actions/runs/5975560139/job/16211777686. Checking. Not sure if related to https://github.com/asyncapi/parser-go/issues/197

**Comment by smoya** [comment]
> Not sure if related to #197

I guess yes:

> Every single workflow that uses [setup-node](https://github.com/actions/setup-node) action needs an update to follow v3 version of this action, and make sure minimum node 14 is used

Fixing!

**Comment by smoya** [comment]
Finally, a new version has been released: https://github.com/asyncapi/parser-go/releases/tag/v0.5.0

Feel free to close this issue @ivan-penchev if you confirm it all works as expected.

**Comment by ivan-penchev** [comment]
Thank you!
