### ISSUE TITLE
Create Protobuf schema parser

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/parser-go#22]
Create Protobuf to JSON Schema Draft 07 converter. It should have a single method as follows:

```go
.Parse(schema []byte) (result json.RawMessage, error)
```

`result` must be a JSON Schema Draft 07-compatible of type `json.RawMessage`.

### References

* https://github.com/chrusty/protoc-gen-jsonschema

**Comment by derberg** [comment]
I think we can close this one, we do not support protobuf in the spec

**Comment by fmvilas** [comment]
No, that's fine. We can keep this closed 👍
