### ISSUE TITLE
What schema versions are supported by this tool?

### ISSUE THREAD

**Issue by armhzjz** [asyncapi/parser-go#52]
It'd be helpful to document (on the README.md file) the schema versions that are currently supported by the tool (i.e. AsyncAPI version 2.0.0).

**Comment by derberg** [comment]
@armhzjz you are absolutely right, would you mind opening a PR with a note similar to the one from JS Parser -> https://github.com/asyncapi/parser-js/ ? there is also a ling to Go converter

**Comment by armhzjz** [comment]
Hi @derberg. I have created the PR. I am getting an error message that goes:
"Resource not accessible by integration"
Do I get this due to a lack of permissions / rights to the repository or have I done something wrong?
(I googled it and it seems it is in deed my lack of permissions, but wanted to clarify with you).

**Comment by derberg** [comment]
@armhzjz do not worry about this failing job. I described the issue here https://github.com/asyncapi/html-template/issues/61#issuecomment-691062432

**Comment by derberg** [comment]
@armhzjz thanks a lot for your PR!

**Comment by armhzjz** [comment]
Thanks to you guys!
:)
